# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GaoDeLocationFailed' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for GaoDeLocationFailed

#pod 'AFNetworking'
#pod 'ReactiveCocoa'
#pod 'MBProgressHUD', '~> 0.9.2'
pod 'PureLayout'
#pod 'SDWebImage', '~>3.8'
#pod 'FMDB'
#pod ‘iOS-Slide-Menu’

pod 'AMap2DMap'
pod 'AMapSearch'
#pod 'MJRefresh’

end
